FROM ubuntu:20.04
MAINTAINER Dmitry Lavnikevich <dmitry.lavnikevich@scalys.com>

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    sudo \
    build-essential \
    curl \
    libcurl4-openssl-dev \
    libssl-dev \
    wget \
    python3 \
    python3-pip \
    python3-dev \
    git \
    tar \
    libatlas-base-dev \
    cmake \
    bison \
    flex \
    python3-pip \
    bc

# Set up user
ARG USER
ARG UID
ARG GID
RUN groupadd ${USER} --gid ${GID}
RUN useradd -m ${USER} --uid=${UID} --gid=${GID}
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY files/scripts /tmp/openenclave-scripts
RUN /tmp/openenclave-scripts/ansible/install-ansible.sh
RUN ansible-playbook /tmp/openenclave-scripts/ansible/oe-contributors-setup-cross-arm.yml
RUN pip install pycryptodomex pyelftools
RUN pip install pillow

# VSCode extension build dependencies
COPY files/scripts /tmp/openenclave-scripts
RUN apt-get update && \
    curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nodejs
RUN npm install -g --unsafe-perm vsce
RUN npm install -g --unsafe-perm esy

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ocaml-native-compilers \
    gawk \
    vim \
    llvm

# Set up prompt
RUN echo 'export PS1="\h:\W# "' | tee -a "/root/.bashrc" > /dev/null
RUN echo 'export PS1="\h:\W$ "' | tee -a "/home/${USER}/.bashrc" > /dev/null

# Dependencies for Yucto build
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    chrpath cpio diffstat
RUN apt-get update && \
    apt-get install -y locales && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen
ENV LC_ALL "en_US.UTF-8"
ENV LANG "en_US.UTF-8"
ENV LANGUAGE "en_US.UTF-8"

# Needed for Yocto build of optee/oe
# TODO: check which one
RUN pip install pycryptodome
RUN pip3 install pycryptodome

USER "${USER}"

# Install toolchain
RUN cd && \
    echo "Downloading toolchain..." && \
    wget -q http://trustbox.scalys.com/pub/openenclave/poky-glibc-x86_64-scalys-openenclave-image-aarch64-trustsom-toolchain-ext-3.1.10.sh -O toolchain.sh
RUN cd && chmod +x toolchain.sh && \
    ./toolchain.sh -y && \
    rm -f toolchain.sh

# Install rutstup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y
RUN /home/haff/.cargo/bin/rustup target add aarch64-unknown-linux-gnu
RUN sudo cp -a /etc/ssl /home/haff/poky_sdk/buildtools/sysroots/x86_64-pokysdk-linux/etc/

